#!/bin/bash

DBAL_REPOSITORY_SHORTNAME='arlekin-dbal'
DOCKER_DEV_REPOSITORY_SHORTNAME='docker-arlekin-dev'

REPOSITORIES=$DBAL_REPOSITORY_SHORTNAME" "$DOCKER_DEV_REPOSITORY_SHORTNAME
FOLDERS=$REPOSITORIES
