#!/bin/bash

ARLEKIN_DBAL_REPOSITORY_SHORTNAME='arlekin-dbal'
ARLEKIN_DOCKER_REPOSITORY_SHORTNAME='docker-arlekin-dev'

ARLEKIN_REPOSITORIES=$ARLEKIN_DBAL_REPOSITORY_SHORTNAME" "$ARLEKIN_DOCKER_REPOSITORY_SHORTNAME 
ARLEKIN_FOLDERS=$ARLEKIN_REPOSITORIES

